# Generated by Django 5.2.4 on 2025-08-02 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_deleted_at_category_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Цвет в формате HEX', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 11, 8, 26, 549066, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 11, 9, 16, 972946, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления'),
            preserve_default=False,
        ),
    ]
