# Generated by Django 5.2.4 on 2025-08-02 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(max_length=20, verbose_name='New Status')),
                ('notification_type', models.CharField(choices=[('status_change', 'Status Change'), ('task_completed', 'Task Completed'), ('status_reverted', 'Status Reverted')], default='status_change', max_length=50, verbose_name='Notification Type')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_notifications', to='myapp.task', verbose_name='Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Status Change Notification',
                'verbose_name_plural': 'Status Change Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
